import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['eslint', 'import', 'jsdoc', 'oxc', 'promise', 'typescript', 'unicorn', 'node'],
  jsPlugins: [
    '@stylistic/eslint-plugin',
    {
      name: 'anti-slop',
      specifier: '@devlsh/tools/oxlint/anti-slop',
    },
  ],
  options: {
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
    typeCheck: false,
  },
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
  ],
  rules: {
    'anti-slop/no-array-filter-map': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reduce-accumulator-copy': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-readable-spacing': 'off',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
    '@stylistic/object-curly-newline': [
      'error',
      {
        ObjectExpression: {
          minProperties: 2,
          consistent: true,
        },
        TSTypeLiteral: {
          multiline: true,
          consistent: true,
        },
        TSInterfaceBody: {
          minProperties: 2,
          consistent: true,
        },
      },
    ],
    '@stylistic/object-property-newline': [
      'error',
      {
        allowAllPropertiesOnSameLine: true,
      },
    ],
    '@stylistic/padding-line-between-statements': [
      'error',
      {
        blankLine: 'always',
        prev: 'import',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: { selector: 'Program > :not(ImportDeclaration)' },
      },
      {
        blankLine: 'always',
        prev: { selector: 'Program > :not(ImportDeclaration)' },
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: ['function', 'class', 'interface', 'type'],
      },
      {
        blankLine: 'always',
        prev: ['function', 'class', 'interface', 'type'],
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: ['multiline-const', 'multiline-let', 'multiline-var', 'multiline-using'],
      },
      {
        blankLine: 'always',
        prev: ['multiline-const', 'multiline-let', 'multiline-var', 'multiline-using'],
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: ['return', 'if', 'switch', 'try', 'for', 'while', 'do'],
      },
      {
        blankLine: 'always',
        prev: 'block-like',
        next: '*',
      },
      {
        blankLine: 'any',
        prev: 'import',
        next: 'import',
      },
      {
        blankLine: 'any',
        prev: {
          selector: ':matches(TSDeclareFunction, ExportNamedDeclaration[declaration.type="TSDeclareFunction"])',
        },
        next: {
          selector:
            ':matches(TSDeclareFunction, FunctionDeclaration, ExportNamedDeclaration[declaration.type="TSDeclareFunction"], ExportNamedDeclaration[declaration.type="FunctionDeclaration"])',
        },
      },
    ],
    'block-scoped-var': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'eslint/array-callback-return': [
      'error',
      {
        allowImplicit: false,
        allowVoid: false,
        checkForEach: true,
      },
    ],
    'eslint/curly': ['error', 'all'],
    'eslint/eqeqeq': 'error',
    'eslint/grouped-accessor-pairs': [
      'error',
      'getBeforeSet',
      {
        enforceForTSTypes: true,
      },
    ],
    'eslint/logical-assignment-operators': [
      'error',
      'always',
      {
        enforceForIfStatements: false,
      },
    ],
    'eslint/max-classes-per-file': [
      'error',
      {
        ignoreExpressions: true,
        max: 6,
      },
    ],
    'eslint/max-params': [
      'error',
      {
        countThis: 'except-void',
        max: 4,
      },
    ],
    'eslint/no-duplicate-imports': [
      'error',
      {
        allowSeparateTypeImports: false,
        includeExports: false,
      },
    ],
    'eslint/no-else-return': [
      'error',
      {
        allowElseIf: true,
      },
    ],
    'eslint/no-empty-function': [
      'error',
      {
        allow: [
          'methods',
          'asyncMethods',
          'constructors',
          'privateConstructors',
          'protectedConstructors',
          'overrideMethods',
        ],
      },
    ],
    'eslint/no-extend-native': 'error',
    'eslint/no-fallthrough': [
      'error',
      {
        allowEmptyCase: true,
        commentPattern: 'falls?\\s?through',
        reportUnusedFallthroughComment: true,
      },
    ],
    'eslint/no-implicit-coercion': [
      'error',
      {
        allow: [],
        boolean: true,
        disallowTemplateShorthand: false,
        number: true,
        string: true,
      },
    ],
    'eslint/no-implicit-globals': [
      'error',
      {
        lexicalBindings: true,
      },
    ],
    'eslint/no-labels': [
      'error',
      {
        allowLoop: false,
        allowSwitch: false,
      },
    ],
    'eslint/no-multi-assign': 'error',
    'eslint/no-promise-executor-return': [
      'error',
      {
        allowVoid: false,
      },
    ],
    'eslint/no-redeclare': [
      'error',
      {
        builtinGlobals: true,
      },
    ],
    'eslint/no-return-assign': ['error', 'always'],
    'eslint/no-sequences': [
      'error',
      {
        allowInParentheses: false,
      },
    ],
    'eslint/no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: true,
      },
    ],
    'eslint/no-unused-vars': [
      'error',
      {
        vars: 'all',
        args: 'all',
        caughtErrors: 'all',
        varsIgnorePattern: '^_',
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreClassWithStaticInitBlock: false,
        ignoreRestSiblings: false,
        ignoreUsingDeclarations: false,
        reportUsedIgnorePattern: true,
        reportVarsOnlyUsedAsTypes: true,
        fix: {
          imports: 'safe-fix',
          variables: 'suggestion',
        },
      },
    ],
    'eslint/no-use-before-define': [
      'error',
      {
        allowNamedExports: true,
        classes: true,
        enums: true,
        functions: false,
        ignoreTypeReferences: true,
        typedefs: false,
        variables: false,
      },
    ],
    'eslint/no-useless-computed-key': [
      'error',
      {
        enforceForClassMembers: true,
      },
    ],
    'eslint/object-shorthand': [
      'error',
      'always',
      {
        avoidExplicitReturnArrows: false,
        avoidQuotes: true,
        ignoreConstructors: false,
      },
    ],
    'eslint/operator-assignment': ['error', 'always'],
    'eslint/prefer-destructuring': [
      'error',
      {
        VariableDeclarator: {
          array: false,
          object: true,
        },
        AssignmentExpression: {
          array: false,
          object: false,
        },
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    'eslint/prefer-promise-reject-errors': 'error',
    'eslint/prefer-regex-literals': [
      'error',
      {
        disallowRedundantWrapping: true,
      },
    ],
    'eslint/preserve-caught-error': 'error',
    'eslint/radix': ['error', 'always'],
    'eslint/require-yield': 'off',
    'eslint/require-unicode-regexp': [
      'error',
      {
        requireFlag: 'u',
      },
    ],
    'eslint/unicode-bom': ['error', 'never'],
    'eslint/yoda': ['error', 'never'],
    'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': [
      'error',
      'never',
      {
        ignorePackages: true,
        checkTypeImports: false,
        pathGroupOverrides: [
          {
            pattern: '**/*.{css,json,frag,png,vert}',
            action: 'ignore',
          },
          {
            pattern: '**/*.{css,json,frag,png,vert}?*',
            action: 'ignore',
          },
        ],
      },
    ],
    'import/first': 'error',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/newline-after-import': 'error',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-anonymous-default-export': [
      'error',
      {
        allowAnonymousClass: false,
        allowAnonymousFunction: false,
        allowArray: false,
        allowArrowFunction: false,
        allowCallExpression: false,
        allowLiteral: false,
        allowNew: false,
        allowObject: false,
      },
    ],
    'import/no-commonjs': [
      'error',
      {
        allowConditionalRequire: false,
        allowPrimitiveModules: false,
        allowRequire: false,
      },
    ],
    'import/no-cycle': 'error',
    'import/no-default-export': 'off',
    'import/no-duplicates': 'error',
    'import/no-dynamic-require': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-named-default': 'error',
    'import/no-self-import': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/empty-tags': 'error',
    'jsdoc/no-blank-blocks': ['error', { enableFixer: true }],
    'jsdoc/require-param-name': 'error',
    'jsdoc/require-throws-description': 'error',
    'jsdoc/require-yields-description': 'error',
    'jsx_a11y/aria-props': 'error',
    'jsx_a11y/aria-role': 'error',
    'jsx_a11y/iframe-has-title': 'error',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-case-declarations': 'error',
    'no-constant-binary-expression': 'error',
    'no-constructor-return': 'error',
    'no-div-regex': 'error',
    'no-eq-null': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-eval': [
      'error',
      {
        allowIndirect: false,
      },
    ],
    'no-irregular-whitespace': [
      'error',
      {
        skipComments: false,
        skipJSXText: false,
        skipRegExps: false,
        skipStrings: false,
        skipTemplates: false,
      },
    ],
    'no-negated-condition': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-optional-chaining': [
      'error',
      {
        disallowArithmeticOperators: true,
      },
    ],
    'no-useless-assignment': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'node/handle-callback-err': ['error', '^(err|error)$'],
    'node/no-mixed-requires': 'error',
    'node/no-path-concat': 'error',
    'node/no-sync': 'error',
    'oxc/approx-constant': 'error',
    'oxc/bad-bitwise-operator': 'error',
    'oxc/branches-sharing-code': 'error',
    'oxc/misrefactored-assign-op': 'error',
    'oxc/no-accumulating-spread': 'error',
    'oxc/no-const-enum': 'error',
    'oxc/no-map-spread': [
      'error',
      {
        ignoreArgs: false,
        ignoreRereads: true,
      },
    ],
    'oxc/no-this-in-exported-function': 'error',
    'prefer-exponentiation-operator': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'promise/catch-or-return': [
      'error',
      {
        allowFinally: true,
        allowThen: true,
        allowThenStrict: false,
        terminationMethod: ['catch'],
      },
    ],
    'promise/no-callback-in-promise': 'error',
    'promise/no-multiple-resolved': 'error',
    'promise/no-nesting': 'error',
    'promise/no-new-statics': 'error',
    'promise/no-return-in-finally': 'error',
    'promise/no-return-wrap': 'error',
    'promise/prefer-catch': 'error',
    'promise/spec-only': 'error',
    'react/button-has-type': 'error',
    'react/checked-requires-onchange-or-readonly': 'error',
    'react/exhaustive-deps': 'error',
    'react/forward-ref-uses-ref': 'error',
    'react/iframe-missing-sandbox': 'error',
    'react/jsx-boolean-value': ['error', 'never'],
    'react/jsx-curly-brace-presence': [
      'error',
      {
        props: 'never',
        children: 'never',
        propElementValues: 'always',
      },
    ],
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-constructed-context-values': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-script-url': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-useless-fragment': 'error',
    'react/jsx-pascal-case': [
      'error',
      {
        allowAllCaps: true,
      },
    ],
    'react/jsx-props-no-spread-multi': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-multi-comp': [
      'error',
      {
        ignoreStateless: true,
      },
    ],
    'react/no-namespace': 'error',
    'react/no-unknown-property': [
      'error',
      {
        requireDataLowercase: true,
      },
    ],
    'react/function-component-definition': [
      'error',
      {
        namedComponents: 'function-declaration',
        unnamedComponents: 'function-expression',
      },
    ],
    'react/prefer-function-component': 'error',
    'react/capitalized-calls': 'error',
    'react/error-boundaries': 'error',
    'react/globals': 'error',
    'react/hooks': 'error',
    'react/immutability': 'error',
    'react/invariant': 'error',
    'react/no-deriving-state-in-effects': 'error',
    'react/preserve-manual-memoization': 'error',
    'react/purity': 'error',
    'react/refs': 'error',
    'react/rule-suppression': 'error',
    'react/set-state-in-effect': 'error',
    'react/set-state-in-render': 'error',
    'react/static-components': 'error',
    'react/syntax': 'error',
    'react/use-memo': 'error',
    'react/void-use-memo': 'error',
    'react/rules-of-hooks': 'error',
    'react/self-closing-comp': 'error',
    'react/style-prop-object': 'error',
    'react/void-dom-elements-no-children': 'error',
    'symbol-description': 'error',
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/array-type': [
      'error',
      {
        default: 'array',
        readonly: 'array',
      },
    ],
    'typescript/consistent-type-definitions': ['error', 'interface'],
    'typescript/consistent-type-exports': [
      'error',
      {
        fixMixedExportsWithInlineTypeSpecifier: true,
      },
    ],
    'typescript/consistent-type-imports': [
      'error',
      {
        prefer: 'type-imports',
        fixStyle: 'inline-type-imports',
        disallowTypeAnnotations: true,
      },
    ],
    'typescript/dot-notation': 'error',
    'typescript/explicit-member-accessibility': [
      'error',
      {
        accessibility: 'no-public',
      },
    ],
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-confusing-void-expression': [
      'error',
      {
        ignoreArrowShorthand: true,
        ignoreVoidOperator: true,
        ignoreVoidReturningFunctions: false,
      },
    ],
    'typescript/no-deprecated': 'error',
    'typescript/no-empty-interface': 'error',
    'typescript/no-inferrable-types': [
      'error',
      {
        ignoreParameters: false,
        ignoreProperties: false,
      },
    ],
    'typescript/no-misused-promises': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-qualifier': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-arguments': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/only-throw-error': [
      'error',
      {
        allowRethrowing: false,
        allowThrowingAny: false,
        allowThrowingUnknown: false,
      },
    ],
    'typescript/parameter-properties': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-includes': 'error',
    'typescript/prefer-nullish-coalescing': 'error',
    'typescript/prefer-optional-chain': [
      'error',
      {
        requireNullish: true,
        allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing: false,
      },
    ],
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/prefer-readonly': 'error',
    'typescript/prefer-ts-expect-error': 'error',
    'typescript/promise-function-async': 'error',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/restrict-plus-operands': [
      'error',
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
        skipCompoundAssignments: false,
      },
    ],
    'typescript/return-await': ['error', 'error-handling-correctness-only'],
    'typescript/require-array-sort-compare': [
      'error',
      {
        ignoreStringArrays: false,
      },
    ],
    'typescript/strict-void-return': 'error',
    'typescript/switch-exhaustiveness-check': 'error',
    'typescript/unbound-method': 'off',
    'typescript/unified-signatures': 'error',
    'typescript/use-unknown-in-catch-callback-variable': 'error',
    'unicorn/catch-error-name': 'error',
    'unicorn/consistent-assert': 'error',
    'unicorn/consistent-date-clone': 'error',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-existence-index-check': 'error',
    'unicorn/consistent-template-literal-escape': 'error',
    'unicorn/empty-brace-spaces': 'error',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/explicit-length-check': 'error',
    'unicorn/explicit-timer-delay': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-fill-with-reference-type': 'error',
    'unicorn/no-array-for-each': 'error',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-array-sort': 'error',
    'unicorn/no-await-expression-member': 'error',
    'unicorn/no-confusing-array-with': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-instanceof-array': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/no-this-assignment': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unreadable-iife': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-bigint-literals': 'error',
    'unicorn/prefer-blob-reading-methods': 'error',
    'unicorn/prefer-class-fields': 'error',
    'unicorn/prefer-classlist-toggle': 'error',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-default-parameters': 'error',
    'unicorn/prefer-dom-node-text-content': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-keyboard-event-key': 'error',
    'unicorn/prefer-logical-operator-over-ternary': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-response-static-json': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-single-call': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-string-raw': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-ternary': ['error', 'only-single-line'],
    'unicorn/relative-url-style': ['error', 'always'],
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/require-post-message-target-origin': 'error',
    'unicorn/switch-case-braces': ['error', 'avoid'],
    'unicorn/text-encoding-identifier-case': 'error',
    'use-isnan': [
      'error',
      {
        enforceForIndexOf: true,
      },
    ],
    'valid-typeof': [
      'error',
      {
        requireStringLiterals: true,
      },
    ],
    'vars-on-top': 'error',
    'vue/component-definition-name-casing': ['error', 'PascalCase'],
    'vue/define-emits-declaration': ['error', 'type-based'],
    'vue/define-props-declaration': ['error', 'type-based'],
    'vue/define-props-destructuring': ['error', { destructure: 'never' }],
    'vue/max-props': 'off',
    'vue/next-tick-style': ['error', 'promise'],
    'vue/no-arrow-functions-in-watch': 'error',
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-computed-properties-in-data': 'error',
    'vue/no-deprecated-data-object-declaration': 'error',
    'vue/no-deprecated-delete-set': 'error',
    'vue/no-deprecated-destroyed-lifecycle': 'error',
    'vue/no-deprecated-events-api': 'error',
    'vue/no-deprecated-model-definition': ['error', { allowVue3Compat: false }],
    'vue/no-deprecated-props-default-this': 'error',
    'vue/no-deprecated-vue-config-keycodes': 'error',
    'vue/no-dupe-keys': 'error',
    'vue/no-export-in-script-setup': 'error',
    'vue/no-expose-after-await': 'error',
    'vue/no-import-compiler-macros': 'error',
    'vue/no-lifecycle-after-await': 'error',
    'vue/no-multiple-slot-args': 'error',
    'vue/no-required-prop-with-default': 'error',
    'vue/no-reserved-component-names': [
      'error',
      {
        disallowVueBuiltInComponents: true,
        disallowVue3BuiltInComponents: true,
      },
    ],
    'vue/no-reserved-keys': 'error',
    'vue/no-reserved-props': ['error', { vueVersion: 3 }],
    'vue/no-shared-component-data': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-watch-after-await': 'error',
    'vue/prefer-import-from-vue': 'error',
    'vue/prop-name-casing': ['error', 'camelCase'],
    'vue/require-default-export': 'error',
    'vue/require-default-prop': 'error',
    'vue/require-direct-export': 'error',
    'vue/require-prop-type-constructor': 'error',
    'vue/require-prop-types': 'error',
    'vue/require-render-return': 'error',
    'vue/require-slots-as-functions': 'error',
    'vue/require-typed-ref': 'error',
    'vue/return-in-computed-property': 'error',
    'vue/return-in-emits-validator': 'error',
    'vue/valid-define-emits': 'error',
    'vue/valid-define-options': 'error',
    'vue/valid-define-props': 'error',
    'vue/valid-next-tick': 'error',
  },
  overrides: [
    {
      files: ['**/*.config.ts'],
      rules: {
        'import/no-anonymous-default-export': 'off',
        'import/no-default-export': 'off',
      },
    },
  ],
  env: {
    builtin: true,
  },
});
